Improve Arabic language
EvanHahn/HumanizeDuration.js pull request #193
Opened 2021-01-01 08:55 UTC by ahmadf16

Hay I have been used this library for long quit of time and I want to improve my main language in this library so I have made some changes that  make it consistent with Arabic grammars.

2021-01-01 17:34 UTC, EvanHahn requested changes
Thank you!

Please run `npm run format`. I will do a more thorough review then.

2021-01-14 11:30 UTC, ahmadf16 commented
Done. Sorry for being late.

2021-01-14 20:03 UTC, EvanHahn commented
Thank you.

I will take a look soon.

2021-01-17 16:46 UTC, EvanHahn requested changes
Please update the tests. Also, please address my inline comments.

Thank you! Let me know if I can help.

2021-01-17 16:46 UTC, EvanHahn commented on humanize-duration.js
> +        humanizerOptions.delimiter = " و ";
This should instead be a property on the `ar` language so that other languages can use it.

2021-01-17 16:46 UTC, EvanHahn commented on humanize-duration.js
> +    }
Is there a way to make this more generic, as part of the `ar` language object?

2021-02-23 18:07 UTC, wesam80 commented
Hi @ahmadf16 any updates on this PR?
Thanks both @EvanHahn and @ahmadf16 for your work

2022-05-20 18:57 UTC, EvanHahn commented
@ahmadf16 There have not been updates for over a year, so I am going to close this. Please feel free to reopen!

2022-05-20 18:57 UTC, closed without merging