Arabic translation enhancement: Hide unit count with dual forms.
EvanHahn/HumanizeDuration.js pull request #222
Opened 2024-05-14 03:53 UTC by 6km

The issue with is described in #221.
I have implemented a solution for it.

- **Adds a property to the Arabic humanizer** called `hideUnitInDualForm` that I used to indicate that the language is Arabic.
![image](https://github.com/EvanHahn/HumanizeDuration.js/assets/62352949/2c65525b-b01f-4cb8-a023-94005474e793)

- **Adds a new option**, which is `arabic_hideUnitInDualForm`, it works only with Arabic language.
*default:* `true`.
![image](https://github.com/EvanHahn/HumanizeDuration.js/assets/62352949/263ceae5-6442-440c-831b-fd42bc42e644)

I could just check if the language equals `ar`, but I thought it would be better to add that `hideUnitInDualForm` property to the humanizer and options!

2024-05-16 03:35 UTC, EvanHahn commented
Thank you! I will take a look soon.

2024-05-23 14:51 UTC, EvanHahn requested changes
- I don't know much about Arabic. Do you have a place I could learn more about these rules to make sure this is correct for all Arabic speakers?

- Please run `npm format` to format the code.

- It looks like tests are failing. Could you run `npm test` to make the tests pass?

2024-05-23 14:51 UTC, EvanHahn commented on humanize-duration.js
> +		hideUnitInDualForm: true,
Could you make this a private option, `_hideCountIf2`?

2024-05-23 14:51 UTC, EvanHahn commented on humanize-duration.js
I think you can remove this and just use `options._hideCountIf2`.

2024-05-23 15:46 UTC, 6km commented
@EvanHahn Thanks for your review! I'm working work on it!

> * I don't know much about Arabic. Do you have a place I could learn more about these rules to make sure this is correct for all Arabic speakers?

I didn't find many English resources talking about the dual nouns (Muthanna) in Arabic, but this can help I guess.
[Number: Singular, Dual, Plural Noun in Arabic](https://learnarabicstepbystep.blogspot.com/2018/11/number-singular-dual-plural-arabic-noun.html#:~:text=dual%2C%20or%20plural.-,Dual%20noun,-Dual%20is%20used)

2024-05-23 17:59 UTC, EvanHahn commented
Thanks! I'll take another look soon.

2024-05-25 15:42 UTC, merged

2024-05-25 15:52 UTC, EvanHahn commented
This was released in `humanize-duration@3.32.1`. Thanks for your contribution!

2024-05-25 16:13 UTC, 6km commented
> This was released in `humanize-duration@3.32.1`. Thanks for your contribution!

You're welcome!